language: java
script: "./gradlew --stacktrace bintrayUpload"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: iWJNBPYH666h1hOBRL9EuCz6Jrf9Ci4tR+8YKKuRDVopVjaSSQRKRdxOY1CZwnZF7Yj/RNZvxp3dmAtA8WrO7D58dB+bgvxHwj/HBP3Qi7tXVJNgQw+jBin9CCYgILKkfMO3/6dvOUlloOM4yUir3PLYPueVL1asipD+XQxOlqE=
  - secure: TY06+E7pWIeQx0AY6PN5VDy1XmWtIFTS8n9XsaTV+sgQANtgsDih38GGan83dcDGImUVsY55DmXfHVW81Jni2AQA/0L8QO8jxnkAo3EhmcuexSmGLKXLZ6Xg79wV/oXel5xeFZckCCX79xbo9XUhsGUgj38MWvSjN5+DzPJKfVI=
